AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ApiKeyValue:
    Type: String
    NoEcho: true
    Description: "API Key for the AppnameBananasService"

Resources:
  AppnameBananasService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for CRUD operations"
    Properties:
      Name: "appname-bananas-service"
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS, POST, GET, PUT, DELETE'"
        AllowHeaders: "'Content-Type, x-api-key'"
        AllowOrigin: "'http://localhost:3000'" # replace for production
      Auth:
        ApiKeyRequired: true

  AppnameUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: "AppnameUsagePlan"
      ApiStages:
        - ApiId: !Ref AppnameBananasService
          Stage: Prod
      Throttle:
        RateLimit: 100  # 100 requests per second
        BurstLimit: 20  # 20 immediate burst
      Quota:
        Limit: 10000    # 10,000 requests
        Period: MONTH

  AppnameApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: "AppnameApiKey"
      Enabled: true
      Value: !Ref ApiKeyValue
      StageKeys:
        - RestApiId: !Ref AppnameBananasService
          StageName: Prod
      UsagePlanId: !Ref AppnameUsagePlan

  AppnameBananasFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 512
      Policies:
        - AWSLambdaExecute
        - SecretsManagerReadWrite
        - DynamoDBCrudPolicy:
            TableName: !Ref AppnameBananasTable
      Events:
        BananasOptions:
          Type: Api
          Properties:
            Path: /bananas
            Method: OPTIONS
            RestApiId: !Ref AppnameBananasService
        GetBanana:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: GET
            RestApiId: !Ref AppnameBananasService
        GetBananas:
          Type: Api
          Properties:
            Path: /bananas
            Method: GET
            RestApiId: !Ref AppnameBananasService
        PutBanana:
          Type: Api
          Properties:
            Path: /bananas
            Method: POST
            RestApiId: !Ref AppnameBananasService
        DeleteBanana:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: DELETE
            RestApiId: !Ref AppnameBananasService
        UpdateBanana:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: PUT
            RestApiId: !Ref AppnameBananasService
    Metadata:
      BuildMethod: makefile

  AppnameBananasTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AppnameBananas
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
