AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ApiKeyValue:
    Type: String
    NoEcho: true
    Description: "API Key for the AppnameBananasService"

Resources:
  AppnameBananasService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for CRUD operations"
    Properties:
      Name: "appname-bananas-service"
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS, POST, GET, PUT, DELETE'"
        AllowHeaders: "'Content-Type, x-api-key'"
        AllowOrigin: "'http://localhost:3000'" # replace for production
      Auth:
        ApiKeyRequired: true

  AppnameBananasApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: AppnameBananasServiceProdStage
    Properties:
      Name: "AppnameBananasApiKey"
      Enabled: true
      Value: !Ref ApiKeyValue
      StageKeys:
        - RestApiId: !Ref AppnameBananasService
          StageName: Prod

  AppnameBananasUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: AppnameBananasServiceProdStage
    Properties:
      UsagePlanName: "AppnameBananasUsagePlan"
      ApiStages:
        - ApiId: !Ref AppnameBananasService
          Stage: Prod
      Throttle:
        RateLimit: 100
        BurstLimit: 20
      Quota:
        Limit: 10000
        Period: MONTH

  AppnameBananasUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref AppnameBananasApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref AppnameBananasUsagePlan

  AppnameBananasFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 512
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref AppnameBananasTable
      Events:
        BananasOptions:
          Type: Api
          Properties:
            Path: /bananas
            Method: OPTIONS
            RestApiId: !Ref AppnameBananasService
            Auth:
              ApiKeyRequired: false
        BananasOptionsId:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: OPTIONS
            RestApiId: !Ref AppnameBananasService
            Auth:
              ApiKeyRequired: false
        GetBanana:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: GET
            RestApiId: !Ref AppnameBananasService
            Auth:
              ApiKeyRequired: true
        GetBananas:
          Type: Api
          Properties:
            Path: /bananas
            Method: GET
            RestApiId: !Ref AppnameBananasService
            Auth:
              ApiKeyRequired: true
        PutBanana:
          Type: Api
          Properties:
            Path: /bananas
            Method: POST
            RestApiId: !Ref AppnameBananasService
            Auth:
              ApiKeyRequired: true
        DeleteBanana:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: DELETE
            RestApiId: !Ref AppnameBananasService
            Auth:
              ApiKeyRequired: true
        UpdateBanana:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: PUT
            RestApiId: !Ref AppnameBananasService
            Auth:
              ApiKeyRequired: true
    Metadata:
      BuildMethod: makefile

  AppnameBananasTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AppnameBananas
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
