AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  CfToken:
    Type: String
    NoEcho: true
    Description: Token for API auth (e.g. Cloudflare or custom); set via --parameter-overrides CfToken=xxx when deploying

Resources:
  AppnameBananasService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for CRUD operations"
    Properties:
      Name: "appname-bananas-service"
      StageName: Prod
      Auth:
        # DefaultAuthorizer: AWS_IAM
        # InvokeRole: NONE
      Cors:
        AllowMethods: "'OPTIONS, POST, GET, PUT, DELETE'"
        # AllowHeaders: "'Content-Type, x-amz-content-sha256, x-amz-date, X-Amz-Security-Token, Authorization'"
        AllowHeaders: "'Content-Type, X-CF-Token'"
        # AllowOrigin: "'FRONTEND_URL'" 
        AllowOrigin: "'http://localhost:5173'" 
        # AllowCredentials: true

      # Logging settings
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: true
          DataTraceEnabled: true

  AppnameBananasFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 512
      Environment:
        Variables:
          AWS_CF_TOKEN: !Ref CfToken  # from --parameter-overrides CfToken=xxx; for local use env.json
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref AppnameBananasTable
      Events:
        BananasOptions:
          Type: Api
          Properties:
            Path: /bananas
            Method: OPTIONS
            RestApiId: !Ref AppnameBananasService
            # Auth:
            #   Authorizer: NONE
        BananasOptionsId:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: OPTIONS
            RestApiId: !Ref AppnameBananasService
            # Auth:
            #   Authorizer: NONE
        GetBanana:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: GET
            RestApiId: !Ref AppnameBananasService
            
        GetBananas:
          Type: Api
          Properties:
            Path: /bananas
            Method: GET
            RestApiId: !Ref AppnameBananasService
            
        PutBanana:
          Type: Api
          Properties:
            Path: /bananas
            Method: POST
            RestApiId: !Ref AppnameBananasService
            
        DeleteBanana:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: DELETE
            RestApiId: !Ref AppnameBananasService
            
        UpdateBanana:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: PUT
            RestApiId: !Ref AppnameBananasService
            
    Metadata:
      BuildMethod: makefile

  AppnameBananasTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AppnameBananas
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
